#!/bin/bash
DOTFILES=$("pwd")
GITDIR="${HOME}/git"

echo "The very first thing to do is to install zsh."
sh -c "$(curl -fsSL https://raw.github.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"

echo "Symlinking .zshrc"
rm ${HOME}/.zshrc > /dev/null
cat ${DOTFILES}/zsh/zshrc.plain > ${DOTFILES}/zsh/.zshrc
ln -sf ${DOTFILES}/zsh/.zshrc ${HOME}/.zshrc

echo "Symlinking .vimrc"
rm ${HOME}/.vimrc > /dev/null
cat ${DOTFILES}/vim/vimrc.main > ${DOTFILES}/vim/.vimrc
ln -sf ${DOTFILES}/vim/.vimrc ${HOME}/.vimrc

echo "Linking vim plugin configurations..."
PLUGIN_CONFIGS=$(ls ${DOTFILES}/vim/*.vim)
echo $PLUGIN_CONFIGS
for config in $PLUGIN_CONFIGS
do
	echo "source $config" >> ${HOME}/.vimrc
done

echo "Install Dein.vim (successor of Vundle)"
curl https://raw.githubusercontent.com/Shougo/dein.vim/master/bin/installer.sh > installer.sh
sh ./installer.sh ~/.cache/dein && rm ./installer.sh
nvim +dein#install +qall

echo "Install Znap to manage Zsh plugins."
rm -rf ${GITDIR}/zsh-snap > /dev/null 
git clone --depth 1 -- https://github.com/marlonrichert/zsh-snap.git ${GITDIR}/zsh-snap

echo "Adding znap configuration to .zshrc"
echo "source ${DOTFILES}/zsh/zsh-snap/zshrc.config" >> ${HOME}/.zshrc

echo "source ${DOTFILES}/zsh/zshrc.custom" >> ${HOME}/.zshrc

[ ! -f ${HOME}/.dotfiles ] && touch ${HOME}/.dotfiles
echo "source ${HOME}/.dotfiles" >> ${HOME}/.zshrc

exec $(which zsh) 

